import math

# Game Settings
RATIO = 1
RESOLUTION = WIDTH, HEIGHT = 1600*RATIO, 900*RATIO
FPS = 60

PLAYER_POSITION = 1, 5
PLAYER_ANGLE = 0
PLAYER_SPEED = 0.004
PLAYER_ROT_SPEED = 0.002

FOV = math.pi / 3 # field of view
HALF_FOV = FOV / 2
NUM_RAYS = WIDTH // 2
HALF_NUM_RAYS = NUM_RAYS // 2
DELTA_ANGLE = FOV / NUM_RAYS
MAX_DEPTH = 20